; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Valeurs injectables par la CI via ISCC /D… (replis pour le build manuel) :
;   /DMyAppVersion=10-06-2026     numéro de version (= date de publication)
;   /DDeploySrc=C:\chemin\Deploy   dossier produit par windeployqt (contenu à empaqueter)
#ifndef MyAppVersion
  #define MyAppVersion "23-02-2025"
#endif
#ifndef DeploySrc
  #define DeploySrc "C:\Users\serge\RufusDeploy"
#endif

#define MyAppName "Rufus"
#define MyAppPublisher "RufusVision"
#define MyAppURL "https://www.rufusvision.org/"
#define MyAppExeName "Rufus.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BB737C7D-1DA8-4BB2-9950-DA8781E50453}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=RufusSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
; Sunglasses.ico

[Files]
Source: "{#DeploySrc}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: vc_redist.x64.exe

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


; ─────────────────────────────────────────────────────────────────────────────
;  PRÉ-CONTRÔLE MySQL (avant TOUTE installation : on ne touche pas à l'ancien
;  Rufus tant que le socle MySQL n'est pas validé).
;  Règle : MySQL >= 8.4.3 et PAS MariaDB. mysqld --version est « brutal » :
;   • répond >= 8.4.3      -> serveur local OK (install/MAJ monoposte) -> on continue
;   • répond < 8.4.3/Maria -> message de migration -> on ABANDONNE l'install
;   • ne répond pas         -> pas de MySQL local : 1re install OU client réseau
;                              -> 3 boutons (dont certification = trace légale .certif)
; ─────────────────────────────────────────────────────────────────────────────
[Code]
const
  MIN_MAJOR = 8; MIN_MINOR = 4; MIN_PATCH = 3;

function LitSortie(const Cmd: String; var Output: String): Boolean;
var TmpFile: String; Code: Integer; A: AnsiString;
begin
  Result := False; Output := '';
  TmpFile := ExpandConstant('{tmp}\rufus_mysqld.txt');
  if Exec(ExpandConstant('{cmd}'), '/C ' + Cmd + ' > "' + TmpFile + '" 2>&1', '',
          SW_HIDE, ewWaitUntilTerminated, Code) then
    if LoadStringFromFile(TmpFile, A) then begin Output := String(A); Result := True; end;
  DeleteFile(TmpFile);
end;

// Extrait le 1er "entier.entier.entier" trouvé à partir de la position P.
function ExtraitVersion(const S: String; var Maj, Min, Pat: Integer): Boolean;
var i, n, val, champ: Integer; c: Char;
begin
  Result := False; Maj := 0; Min := 0; Pat := 0; champ := 0; val := 0; n := 0;
  for i := 1 to Length(S) do begin
    c := S[i];
    if (c >= '0') and (c <= '9') then begin val := val*10 + (Ord(c)-Ord('0')); n := n+1; end
    else if (c = '.') and (n > 0) then begin
      if champ = 0 then Maj := val else if champ = 1 then Min := val;
      champ := champ+1; val := 0; n := 0;
      if champ > 2 then Break;
    end else begin
      if n > 0 then begin
        if champ = 2 then begin Pat := val; Result := True; Exit; end;
        // séquence d'entiers incomplète : on réinitialise
        champ := 0; val := 0; n := 0;
      end;
    end;
  end;
  if (champ = 2) and (n > 0) then begin Pat := val; Result := True; end;
end;

// 0 = OK (>=8.4.3 MySQL) ; 1 = trop vieux/MariaDB ; 2 = pas de mysqld local
function ControleMySQLLocal(): Integer;
var Sortie: String; Maj, Min, Pat: Integer;   // NB: ne PAS nommer "Out" (mot-clé réservé Pascal)
begin
  Result := 2;
  if not LitSortie('mysqld --version', Sortie) then Exit;
  if Trim(Sortie) = '' then Exit;
  if Pos('mariadb', Lowercase(Sortie)) > 0 then begin Result := 1; Exit; end;
  if not ExtraitVersion(Sortie, Maj, Min, Pat) then Exit;   // version illisible -> traiter comme absent
  if (Maj > MIN_MAJOR)
     or ((Maj = MIN_MAJOR) and (Min > MIN_MINOR))
     or ((Maj = MIN_MAJOR) and (Min = MIN_MINOR) and (Pat >= MIN_PATCH)) then
    Result := 0
  else
    Result := 1;
end;

procedure EcritCertif(const Ligne: String);
var Dir: String;
begin
  Dir := ExpandConstant('{userprofile}\.rufus');
  ForceDirectories(Dir);
  SaveStringToFile(Dir + '\.certif',
    GetDateTimeString('yyyy-mm-dd hh:nn', '-', ':') + ' | ' + Ligne + #13#10, True);
end;

// Un Rufus est-il DÉJÀ installé sur ce poste ? (clé de désinstallation Inno de notre
// AppId, ou Rufus.exe à l'emplacement par défaut). Le contrôle MySQL ne se fait QU'EN
// cas de MAJ : en installation neuve il n'y a rien à détruire, donc rien à vérifier.
function RufusDejaInstalle(): Boolean;
const KEY = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{BB737C7D-1DA8-4BB2-9950-DA8781E50453}_is1';
begin
  Result := FileExists(ExpandConstant('{autopf}\{#MyAppName}\{#MyAppExeName}'))
         or RegKeyExists(HKLM64, KEY) or RegKeyExists(HKLM32, KEY)
         or RegKeyExists(HKCU64, KEY) or RegKeyExists(HKCU32, KEY);
end;

// Rôle du poste d'après rufus.ini : BDD_POSTE Active=YES → ce poste HÉBERGE la base
// (serveur) ; BDD_LOCAL/BDD_DISTANT Active=YES → CLIENT réseau. rufus.ini FAIT FOI sur
// le rôle ; la présence d'un mysqld local n'est qu'un repli quand l'ini est absent/muet.
// Subtilité : l'installeur tourne en mode élevé, mais {userprofile} pointe bien vers le
// profil de l'utilisateur CONNECTÉ (pas celui de l'admin) — c'est le bon rufus.ini.
function RoleDepuisIni(): String;
var ini: String;
begin
  Result := 'INCONNU';
  ini := ExpandConstant('{userprofile}\Documents\Rufus\Rufus.ini');
  if not FileExists(ini) then Exit;
  if Uppercase(Trim(GetIniString('BDD_POSTE', 'Active', '', ini))) = 'YES' then begin
    Result := 'SERVEUR'; Exit;
  end;
  if (Uppercase(Trim(GetIniString('BDD_LOCAL', 'Active', '', ini))) = 'YES')
     or (Uppercase(Trim(GetIniString('BDD_DISTANT', 'Active', '', ini))) = 'YES') then
    Result := 'CLIENT';
end;

// Langue des messages, d'après rufus.ini ([Param_Poste] Version, = Param_Poste_Version côté
// code). Traduit : fr, en, es, pt (br -> pt) ; repli fr pour toute autre / si absent.
function LangueDepuisIni(): String;
var ini, v: String;
begin
  Result := 'fr';
  ini := ExpandConstant('{userprofile}\Documents\Rufus\Rufus.ini');
  if not FileExists(ini) then Exit;
  v := Lowercase(Trim(GetIniString('Param_Poste', 'Version', '', ini)));
  if (v = 'fr') or (v = 'en') or (v = 'es') or (v = 'pt') then Result := v
  else if v = 'br' then Result := 'pt';
end;

// Dialogue de consentement à la mise à jour du socle MySQL (cf. journal, point 1.b), dans la
// langue du poste. On ne traduit QUE ce dialogue : c'est le seul montré quand rufus.ini est
// lisible (donc quand la langue est connue) ; les dialogues de repli (rôle INCONNU) restent en
// français, faute de rufus.ini pour en déduire la langue.
//   True  = l'utilisateur accepte : l'install se fait ; au 1er lancement, Rufus met à jour
//           MySQL automatiquement (sauvegarde validée → réinstall → restauration).
//   False = il reporte : l'installeur stoppe, l'ancien Rufus reste en place.
function ConsentementMajServeur(): Boolean;
var lang, titre, texte, btnOk, btnAnnuler: String;
begin
  lang := LangueDepuisIni();
  if lang = 'en' then begin
    titre := 'MySQL server update';
    texte := 'This computer hosts the patient database.' + #13#10#13#10
      + 'This new version of Rufus strengthens database security by introducing more elaborate '
      + 'password management.' + #13#10#13#10
      + 'It requires an update of the MySQL server: Rufus will uninstall MySQL, reinstall a more '
      + 'recent version, then back up and restore your patient database.' + #13#10#13#10
      + 'This operation may take several minutes depending on the size of your database.' + #13#10#13#10
      + 'IMPORTANT: if the other computers on the local network also use Rufus, they MUST be '
      + 'updated to this new version within one month, otherwise they will no longer work.';
    btnOk := 'OK, continue (Rufus will update MySQL automatically)';
    btnAnnuler := 'Cancel, I will do this later';
  end else if lang = 'es' then begin
    titre := 'Actualización del servidor MySQL';
    texte := 'Este equipo aloja la base de datos de pacientes.' + #13#10#13#10
      + 'Esta nueva versión de Rufus refuerza la seguridad de la base de datos mediante una '
      + 'gestión más elaborada de la contraseña.' + #13#10#13#10
      + 'Requiere actualizar el servidor MySQL: Rufus desinstalará MySQL, reinstalará una versión '
      + 'más reciente y luego hará una copia de seguridad y restaurará su base de datos de pacientes.' + #13#10#13#10
      + 'Esta operación puede durar varios minutos según el tamaño de su base de datos.' + #13#10#13#10
      + 'IMPORTANTE: si los demás equipos de la red local también usan Rufus, deberán actualizarse '
      + 'OBLIGATORIAMENTE a esta nueva versión en el plazo de un mes; de lo contrario, dejarán de funcionar.';
    btnOk := 'Aceptar, continuar (Rufus actualizará MySQL automáticamente)';
    btnAnnuler := 'Cancelar, lo haré más tarde';
  end else if lang = 'pt' then begin
    titre := 'Atualização do servidor MySQL';
    texte := 'Este computador aloja a base de dados de pacientes.' + #13#10#13#10
      + 'Esta nova versão do Rufus reforça a segurança da base de dados através de uma gestão '
      + 'mais elaborada da palavra-passe.' + #13#10#13#10
      + 'Exige uma atualização do servidor MySQL: o Rufus vai desinstalar o MySQL, reinstalar uma '
      + 'versão mais recente e, em seguida, fazer uma cópia de segurança e restaurar a sua base de dados de pacientes.' + #13#10#13#10
      + 'Esta operação pode demorar vários minutos consoante o tamanho da sua base de dados.' + #13#10#13#10
      + 'IMPORTANTE: se os outros computadores da rede local também utilizarem o Rufus, terão '
      + 'OBRIGATORIAMENTE de ser atualizados para esta nova versão no prazo de um mês, caso contrário deixarão de funcionar.';
    btnOk := 'OK, continuar (o Rufus atualizará o MySQL automaticamente)';
    btnAnnuler := 'Cancelar, farei isto mais tarde';
  end else begin
    titre := 'Mise à jour du serveur MySQL';
    texte := 'Ce poste héberge la base de données patients.' + #13#10#13#10
      + 'Cette nouvelle version de Rufus renforce la sécurité de la base en mettant en place '
      + 'une gestion plus élaborée du mot de passe.' + #13#10#13#10
      + 'Elle nécessite une mise à jour du serveur MySQL : Rufus va désinstaller MySQL, '
      + 'réinstaller une version plus récente, puis sauvegarder et restaurer votre base patients.' + #13#10#13#10
      + 'Cette opération peut durer plusieurs minutes selon la taille de votre base.' + #13#10#13#10
      + 'IMPORTANT : si les autres postes du réseau local utilisent aussi Rufus, ils devront '
      + 'IMPÉRATIVEMENT être mis à jour vers cette nouvelle version sous un mois, faute de quoi '
      + 'ils ne pourront plus fonctionner.';
    btnOk := 'OK, continuer (Rufus mettra MySQL à jour automatiquement)';
    btnAnnuler := 'Annuler, je ferai cela plus tard';
  end;
  Result := (TaskDialogMsgBox(titre, texte, mbInformation, 0, [btnOk, btnAnnuler], 0) = 100);
end;

// True = on continue l'installation ; False = on l'abandonne (ancien Rufus intact).
function InitializeSetup(): Boolean;
var etat, btn: Integer; role: String;
begin
  // Installation NEUVE (aucun Rufus préexistant) : rien à détruire → on n'importune
  // pas l'utilisateur, on installe directement.
  if not RufusDejaInstalle() then begin
    Result := True; Exit;
  end;

  role := RoleDepuisIni();

  // Point 1.c : ce poste est un CLIENT réseau (rufus.ini fait foi) → ce n'est pas lui qui
  // héberge la base → on installe sans rien signaler ni contrôler le mysqld local.
  if role = 'CLIENT' then begin
    EcritCertif('CLIENT réseau (rufus.ini BDD_LOCAL/BDD_DISTANT) : installation sans contrôle de version');
    Result := True; Exit;
  end;

  // MISE À JOUR d'un Rufus existant : on protège l'installation qui marche.
  etat := ControleMySQLLocal();

  // Point 1.b : ce poste HÉBERGE la base (rufus.ini BDD_POSTE) → consentement si la version
  // ne convient pas (trop ancienne, MariaDB, ou mysqld introuvable malgré le rôle serveur).
  if role = 'SERVEUR' then begin
    if etat = 0 then begin
      EcritCertif('SERVEUR (rufus.ini BDD_POSTE) : MySQL local >= 8.4.3');
      Result := True; Exit;
    end;
    if ConsentementMajServeur() then begin
      EcritCertif('MAJ acceptée (SERVEUR rufus.ini) : socle MySQL à mettre à jour au 1er lancement');
      Result := True;
    end else begin
      EcritCertif('REPORT (MAJ, SERVEUR rufus.ini) : installation annulée par l''utilisateur');
      Result := False;
    end;
    Exit;
  end;

  // role = INCONNU (pas de rufus.ini exploitable) : repli sur l'heuristique du mysqld local.
  if etat = 0 then begin
    EcritCertif('MAJ - vérifié local : MySQL >= 8.4.3');
    Result := True; Exit;
  end;

  if etat = 1 then begin
    // MySQL local trop ancien (ou MariaDB) : on DEMANDE le consentement (cf. journal, 1.b).
    if ConsentementMajServeur() then begin
      EcritCertif('MAJ acceptée : MySQL local trop ancien, mise à jour auto au 1er lancement');
      Result := True;
    end else begin
      EcritCertif('REPORT (MAJ) : MySQL trop ancien, installation annulée par l''utilisateur');
      Result := False;
    end;
    Exit;
  end;

  // etat = 2 : pas de MySQL local → le Rufus existant est un CLIENT réseau → 2 boutons.
  btn := TaskDialogMsgBox(
    'Vérification de votre serveur MySQL',
    'Cette version de Rufus exige un serveur MySQL 8.4.3 ou supérieur '
      + '(MariaDB non pris en charge).' + #13#10#13#10
      + 'Aucun MySQL n''a été détecté sur cet ordinateur (ce poste se connecte donc à '
      + 'un serveur réseau). Indiquez votre situation :',
    // NB : le '[' du tableau de boutons DOIT rester en fin de ligne. Une ligne du [Code] qui
    // COMMENCE par '[' est prise pour un en-tête de section par Inno → "Invalid section tag".
    mbInformation, 0, [
    'Le serveur réseau est en version >= 8.4.3 (je le certifie)',
     'J''IGNORE la version du serveur'], 0);

  if btn = 100 then begin
    EcritCertif('CERTIFIÉ par l''utilisateur (MAJ) : serveur réseau >= 8.4.3');
    Result := True;
  end else begin
    // 101 (version inconnue) ou fenêtre fermée : on guide et on ABANDONNE.
    MsgBox('Avant de mettre à jour, vérifiez la version de MySQL sur votre SERVEUR :' + #13#10
      + '  • sur le serveur, ouvrez une invite de commandes et tapez : mysqld --version' + #13#10
      + '  • ou dans MySQL Workbench : SELECT VERSION();' + #13#10#13#10
      + 'Elle doit être >= 8.4.3 (et ne pas être MariaDB).' + #13#10#13#10
      + 'Relancez cette mise à jour une fois la vérification faite. '
      + 'Votre version actuelle de Rufus n''a pas été modifiée.',
      mbInformation, MB_OK);
    EcritCertif('ABANDON (MAJ) : version serveur inconnue, vérification demandée');
    Result := False;
  end;
end;
