; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Valeurs injectables par la CI via ISCC /D… (replis pour le build manuel) :
;   /DMyAppVersion=10-06-2026     numéro de version (= date de publication)
;   /DDeploySrc=C:\chemin\Deploy   dossier produit par windeployqt (contenu à empaqueter)
#ifndef MyAppVersion
  #define MyAppVersion "23-02-2025"
#endif
#ifndef DeploySrc
  #define DeploySrc "C:\Users\serge\RufusDeploy"
#endif

#define MyAppName "Rufus"
#define MyAppPublisher "RufusVision"
#define MyAppURL "https://www.rufusvision.org/"
#define MyAppExeName "Rufus.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BB737C7D-1DA8-4BB2-9950-DA8781E50453}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=RufusSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
; Sunglasses.ico

[Files]
Source: "{#DeploySrc}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: vc_redist.x64.exe

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


; ─────────────────────────────────────────────────────────────────────────────
;  PRÉ-CONTRÔLE MySQL (avant TOUTE installation : on ne touche pas à l'ancien
;  Rufus tant que le socle MySQL n'est pas validé).
;  Règle : MySQL >= 8.0.14 et PAS MariaDB. mysqld --version est « brutal » :
;   • répond >= 8.0.14      -> serveur local OK (install/MAJ monoposte) -> on continue
;   • répond < 8.0.14/Maria -> message de migration -> on ABANDONNE l'install
;   • ne répond pas         -> pas de MySQL local : 1re install OU client réseau
;                              -> 3 boutons (dont certification = trace légale .certif)
; ─────────────────────────────────────────────────────────────────────────────
[Code]
const
  MIN_MAJOR = 8; MIN_MINOR = 0; MIN_PATCH = 14;

function LitSortie(const Cmd: String; var Output: String): Boolean;
var TmpFile: String; Code: Integer; A: AnsiString;
begin
  Result := False; Output := '';
  TmpFile := ExpandConstant('{tmp}\rufus_mysqld.txt');
  if Exec(ExpandConstant('{cmd}'), '/C ' + Cmd + ' > "' + TmpFile + '" 2>&1', '',
          SW_HIDE, ewWaitUntilTerminated, Code) then
    if LoadStringFromFile(TmpFile, A) then begin Output := String(A); Result := True; end;
  DeleteFile(TmpFile);
end;

// Extrait le 1er "entier.entier.entier" trouvé à partir de la position P.
function ExtraitVersion(const S: String; var Maj, Min, Pat: Integer): Boolean;
var i, n, val, champ: Integer; c: Char;
begin
  Result := False; Maj := 0; Min := 0; Pat := 0; champ := 0; val := 0; n := 0;
  for i := 1 to Length(S) do begin
    c := S[i];
    if (c >= '0') and (c <= '9') then begin val := val*10 + (Ord(c)-Ord('0')); n := n+1; end
    else if (c = '.') and (n > 0) then begin
      if champ = 0 then Maj := val else if champ = 1 then Min := val;
      champ := champ+1; val := 0; n := 0;
      if champ > 2 then Break;
    end else begin
      if n > 0 then begin
        if champ = 2 then begin Pat := val; Result := True; Exit; end;
        // séquence d'entiers incomplète : on réinitialise
        champ := 0; val := 0; n := 0;
      end;
    end;
  end;
  if (champ = 2) and (n > 0) then begin Pat := val; Result := True; end;
end;

// 0 = OK (>=8.0.14 MySQL) ; 1 = trop vieux/MariaDB ; 2 = pas de mysqld local
function ControleMySQLLocal(): Integer;
var Out: String; Maj, Min, Pat: Integer;
begin
  Result := 2;
  if not LitSortie('mysqld --version', Out) then Exit;
  if Trim(Out) = '' then Exit;
  if Pos('mariadb', Lowercase(Out)) > 0 then begin Result := 1; Exit; end;
  if not ExtraitVersion(Out, Maj, Min, Pat) then Exit;   // version illisible -> traiter comme absent
  if (Maj > MIN_MAJOR)
     or ((Maj = MIN_MAJOR) and (Min > MIN_MINOR))
     or ((Maj = MIN_MAJOR) and (Min = MIN_MINOR) and (Pat >= MIN_PATCH)) then
    Result := 0
  else
    Result := 1;
end;

procedure EcritCertif(const Ligne: String);
var Dir: String;
begin
  Dir := ExpandConstant('{userprofile}\.rufus');
  ForceDirectories(Dir);
  SaveStringToFile(Dir + '\.certif',
    GetDateTimeString('yyyy-mm-dd hh:nn', '-', ':') + ' | ' + Ligne + #13#10, True);
end;

// Un Rufus est-il DÉJÀ installé sur ce poste ? (clé de désinstallation Inno de notre
// AppId, ou Rufus.exe à l'emplacement par défaut). Le contrôle MySQL ne se fait QU'EN
// cas de MAJ : en installation neuve il n'y a rien à détruire, donc rien à vérifier.
function RufusDejaInstalle(): Boolean;
const KEY = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{BB737C7D-1DA8-4BB2-9950-DA8781E50453}_is1';
begin
  Result := FileExists(ExpandConstant('{autopf}\{#MyAppName}\{#MyAppExeName}'))
         or RegKeyExists(HKLM64, KEY) or RegKeyExists(HKLM32, KEY)
         or RegKeyExists(HKCU64, KEY) or RegKeyExists(HKCU32, KEY);
end;

// True = on continue l'installation ; False = on l'abandonne (ancien Rufus intact).
function InitializeSetup(): Boolean;
var etat, btn: Integer;
begin
  // Installation NEUVE (aucun Rufus préexistant) : rien à détruire → on n'importune
  // pas l'utilisateur, on installe directement.
  if not RufusDejaInstalle() then begin
    Result := True; Exit;
  end;

  // MISE À JOUR d'un Rufus existant : on protège l'installation qui marche.
  etat := ControleMySQLLocal();

  if etat = 0 then begin
    EcritCertif('MAJ - vérifié local : MySQL >= 8.0.14');
    Result := True; Exit;
  end;

  if etat = 1 then begin
    MsgBox('Cette version de Rufus exige MySQL 8.0.14 ou supérieur, et n''est pas '
      + 'compatible avec MariaDB.' + #13#10#13#10
      + 'Votre serveur MySQL local est trop ancien (ou est MariaDB).' + #13#10#13#10
      + 'Marche à suivre AVANT de mettre à jour :' + #13#10
      + '  1. Ouvrez votre Rufus actuel et SAUVEGARDEZ votre base ;' + #13#10
      + '  2. mettez MySQL à jour vers 8.4.9 (ou réinstallez proprement) ;' + #13#10
      + '  3. restaurez votre sauvegarde, puis relancez cette mise à jour.' + #13#10#13#10
      + 'Mise à jour annulée : votre version actuelle de Rufus n''a pas été modifiée.',
      mbCriticalError, MB_OK);
    EcritCertif('REFUS (MAJ) : MySQL local < 8.0.14 ou MariaDB');
    Result := False; Exit;
  end;

  // etat = 2 : pas de MySQL local → le Rufus existant est un CLIENT réseau → 2 boutons.
  btn := TaskDialogMsgBox(
    'Vérification de votre serveur MySQL',
    'Cette version de Rufus exige un serveur MySQL 8.0.14 ou supérieur '
      + '(MariaDB non pris en charge).' + #13#10#13#10
      + 'Aucun MySQL n''a été détecté sur cet ordinateur (ce poste se connecte donc à '
      + 'un serveur réseau). Indiquez votre situation :',
    mbInformation, 0,
    ['Le serveur réseau est en version >= 8.0.14 (je le certifie)',
     'J''IGNORE la version du serveur'], 0);

  if btn = 100 then begin
    EcritCertif('CERTIFIÉ par l''utilisateur (MAJ) : serveur réseau >= 8.0.14');
    Result := True;
  end else begin
    // 101 (version inconnue) ou fenêtre fermée : on guide et on ABANDONNE.
    MsgBox('Avant de mettre à jour, vérifiez la version de MySQL sur votre SERVEUR :' + #13#10
      + '  • sur le serveur, ouvrez une invite de commandes et tapez : mysqld --version' + #13#10
      + '  • ou dans MySQL Workbench : SELECT VERSION();' + #13#10#13#10
      + 'Elle doit être >= 8.0.14 (et ne pas être MariaDB).' + #13#10#13#10
      + 'Relancez cette mise à jour une fois la vérification faite. '
      + 'Votre version actuelle de Rufus n''a pas été modifiée.',
      mbInformation, MB_OK);
    EcritCertif('ABANDON (MAJ) : version serveur inconnue, vérification demandée');
    Result := False;
  end;
end;
