; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Valeurs injectables par la CI via ISCC /D… (replis pour le build manuel) :
;   /DMyAppVersion=10-06-2026     numéro de version (= date de publication)
;   /DDeploySrc=C:\chemin\Deploy   dossier produit par windeployqt (contenu à empaqueter)
#ifndef MyAppVersion
  #define MyAppVersion "09-07-2025"
#endif
#ifndef DeploySrc
  #define DeploySrc "C:\Users\serge\RufusDeploy"
#endif

#define MyAppName "Rufus"
#define MyAppPublisher "RufusVision"
#define MyAppURL "https://www.rufusvision.org/"
#define MyAppExeName "Rufus.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BB737C7D-1DA8-4BB2-9950-DA8781E50453}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; Empêche le lancement de PLUSIEURS instances simultanées de l'installeur (double-clic répété,
; ou deux sessions utilisateur) : Inno crée ce mutex au démarrage et refuse une 2e instance tant
; que la 1re tourne. Préfixe « Global\ » → vaut pour toutes les sessions de la machine.
SetupMutex=Global\RufusVisionSetupMutex
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=RufusSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
; Raccourci bureau PRÉCOCHÉ (pas de flag « unchecked ») — aligné sur la démarche d'installation.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
; Sunglasses.ico

[Files]
Source: "{#DeploySrc}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: vc_redist.x64.exe

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; « Lancer Rufus » DÉCOCHÉ par défaut (flag « unchecked ») — aligné sur la démarche d'installation.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent unchecked


[UninstallDelete]
; Rufus.ini est créé par l'application (pas par l'installeur) → Inno ne le retire pas tout seul.
; On le supprime à la désinstallation. {%USERPROFILE} vise le profil de l'utilisateur connecté
; (même hypothèse que la lecture de la langue à l'installation).
Type: files; Name: "{%USERPROFILE}\Documents\Rufus\Rufus.ini"


; ─────────────────────────────────────────────────────────────────────────────
;  PRÉ-CONTRÔLE MySQL (avant TOUTE installation : on ne touche pas à l'ancien
;  Rufus tant que le socle MySQL n'est pas validé).
;  LOGIQUE SIMPLIFIÉE (cf. « initialisation Rufus.txt », section I) : on NE devine
;  PLUS le rôle du poste (serveur/client) via rufus.ini. On regarde seulement le
;  MySQL LOCAL, d'après mysqld --version :
;   • répond >= 8.0.14      -> conforme -> on installe ;
;   • ne répond pas         -> pas de MySQL local (MySQL sera posé au 1er lancement) -> on installe ;
;   • répond < 8.0.14/Maria -> avertissement (le 1er lancement proposera une mise à jour qui
;                              efface les données). Le message dit « si vous n'hébergez pas la base
;                              ici, ignorez » : plus besoin de détecter le rôle. Non -> on ABANDONNE.
; ─────────────────────────────────────────────────────────────────────────────
[Code]
const
  MIN_MAJOR = 8; MIN_MINOR = 0; MIN_PATCH = 14;

function LitSortie(const Cmd: String; var Output: String): Boolean;
var TmpFile: String; Code: Integer; A: AnsiString;
begin
  Result := False; Output := '';
  TmpFile := ExpandConstant('{tmp}\rufus_mysqld.txt');
  // /S + commande ENTIÈRE entre guillemets : sinon, avec un chemin mysqld.exe entre guillemets
  // (« C:\Program Files\… ») ET la redirection vers TmpFile (aussi entre guillemets), cmd /C
  // retire les MAUVAIS guillemets (règle des « exactement 2 guillemets ») et la commande casse →
  // version illisible. Avec /S, cmd retire UNIQUEMENT le guillemet de début et de fin de la ligne
  // → tous les guillemets internes sont préservés.
  if Exec(ExpandConstant('{cmd}'), '/S /C "' + Cmd + ' > "' + TmpFile + '" 2>&1"', '',
          SW_HIDE, ewWaitUntilTerminated, Code) then
    if LoadStringFromFile(TmpFile, A) then begin Output := String(A); Result := True; end;
  DeleteFile(TmpFile);
end;

// Extrait le 1er "entier.entier.entier" trouvé à partir de la position P.
function ExtraitVersion(const S: String; var Maj, Min, Pat: Integer): Boolean;
var i, n, val, champ: Integer; c: Char;
begin
  Result := False; Maj := 0; Min := 0; Pat := 0; champ := 0; val := 0; n := 0;
  for i := 1 to Length(S) do begin
    c := S[i];
    if (c >= '0') and (c <= '9') then begin val := val*10 + (Ord(c)-Ord('0')); n := n+1; end
    else if (c = '.') and (n > 0) then begin
      if champ = 0 then Maj := val else if champ = 1 then Min := val;
      champ := champ+1; val := 0; n := 0;
      if champ > 2 then Break;
    end else begin
      if n > 0 then begin
        if champ = 2 then begin Pat := val; Result := True; Exit; end;
        // séquence d'entiers incomplète : on réinitialise
        champ := 0; val := 0; n := 0;
      end;
    end;
  end;
  if (champ = 2) and (n > 0) then begin Pat := val; Result := True; end;
end;

// Analyse la sortie de « <mysqld> --version ».
//   0 = version >= mini ; 1 = trop vieux / MariaDB ; -1 = pas de version exploitable (essayer ailleurs)
function EtatDepuisMysqld(const MysqldCmd: String): Integer;
var Sortie: String; Maj, Min, Pat: Integer;
begin
  Result := -1;
  if not LitSortie(MysqldCmd + ' --version', Sortie) then Exit;
  if Trim(Sortie) = '' then Exit;
  if Pos('mariadb', Lowercase(Sortie)) > 0 then begin Result := 1; Exit; end;
  if not ExtraitVersion(Sortie, Maj, Min, Pat) then Exit;   // « 'mysqld' n'est pas reconnu… » -> -1
  if (Maj > MIN_MAJOR)
     or ((Maj = MIN_MAJOR) and (Min > MIN_MINOR))
     or ((Maj = MIN_MAJOR) and (Min = MIN_MINOR) and (Pat >= MIN_PATCH)) then
    Result := 0
  else
    Result := 1;
end;

// Cherche « <sous-dossier>\bin\mysqld.exe » sous un dossier de base (ex. C:\Program Files\MySQL).
// Renvoie le chemin complet ENTRE GUILLEMETS, ou '' si rien trouvé.
function ChercheMysqldDans(const BaseDir: String): String;
var fr: TFindRec; chemin: String;
begin
  Result := '';
  if not DirExists(BaseDir) then Exit;
  if FindFirst(BaseDir + '\*', fr) then begin
    try
      repeat
        if ((fr.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0)
           and (fr.Name <> '.') and (fr.Name <> '..') then begin
          chemin := BaseDir + '\' + fr.Name + '\bin\mysqld.exe';
          if FileExists(chemin) then begin Result := '"' + chemin + '"'; Exit; end;
        end;
      until not FindNext(fr);
    finally
      FindClose(fr);
    end;
  end;
end;

// mysqld.exe hors PATH : emplacements d'installation standard de MySQL.
function TrouveMysqldHorsPath(): String;
begin
  // {sd} = lecteur système. On vise les VRAIS dossiers « Program Files » (dont les noms ne sont
  // PAS localisés au niveau du système de fichiers), pour ne dépendre ni du mode d'architecture
  // de l'installeur ni de l'ambiguïté de {commonpf}.
  Result := ChercheMysqldDans(ExpandConstant('{sd}\Program Files\MySQL'));
  if Result = '' then
    Result := ChercheMysqldDans(ExpandConstant('{sd}\Program Files (x86)\MySQL'));
end;

// mysqld.exe via le SERVICE Windows : on parcourt les services et on récupère le binaire pointé
// par l'ImagePath de celui qui exécute mysqld.exe. C'est la méthode la PLUS FIABLE — elle donne
// l'emplacement EXACT du serveur qui tourne, indépendamment du PATH, du dossier d'installation et
// du mode d'architecture de l'installeur. Renvoie le chemin ENTRE GUILLEMETS, ou '' si aucun.
function CheminMysqldDepuisService(): String;
var noms: TArrayOfString; i, q: Integer; img, chemin: String;
begin
  Result := '';
  if not RegGetSubkeyNames(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Services', noms) then Exit;
  for i := 0 to GetArrayLength(noms)-1 do begin
    if RegQueryStringValue(HKEY_LOCAL_MACHINE,
         'SYSTEM\CurrentControlSet\Services\' + noms[i], 'ImagePath', img) then begin
      if Pos('mysqld', Lowercase(img)) > 0 then begin
        img := Trim(img);
        if Copy(img, 1, 1) = '"' then begin
          // ImagePath cité : "C:\...\mysqld.exe" --defaults-file="..." → on prend l'intérieur des guillemets.
          q := Pos('"', Copy(img, 2, Length(img)));
          if q > 0 then chemin := Copy(img, 2, q-1) else chemin := '';
        end else begin
          // Non cité : on coupe au 1er espace (cas rare ; les chemins MySQL contiennent des espaces).
          q := Pos(' ', img);
          if q > 0 then chemin := Copy(img, 1, q-1) else chemin := img;
        end;
        if (chemin <> '') and FileExists(chemin) then begin
          Result := '"' + chemin + '"';
          Exit;
        end;
      end;
    end;
  end;
end;

// 0 = OK (>=8.0.14 MySQL) ; 1 = trop vieux/MariaDB ; 2 = pas de mysqld local
// On interroge d'abord le SERVICE Windows (emplacement exact du serveur qui tourne), puis le PATH,
// puis les emplacements d'installation standard : un MySQL installé mais ABSENT du PATH (cas
// fréquent sous Windows) ne doit pas être pris pour « aucun serveur ».
function ControleMySQLLocal(): Integer;
var etat: Integer; chemin: String;
begin
  chemin := CheminMysqldDepuisService();              // 1. via le service Windows (le plus fiable)
  if chemin <> '' then begin
    etat := EtatDepuisMysqld(chemin);
    if etat >= 0 then begin Result := etat; Exit; end;
  end;
  etat := EtatDepuisMysqld('mysqld');                 // 2. via le PATH
  if etat >= 0 then begin Result := etat; Exit; end;
  chemin := TrouveMysqldHorsPath();                   // 3. emplacements standard
  if chemin <> '' then begin
    etat := EtatDepuisMysqld(chemin);
    if etat >= 0 then begin Result := etat; Exit; end;
  end;
  Result := 2;                                         // 4. aucun mysqld détecté
end;

procedure EcritCertif(const Ligne: String);
var Dir: String;
begin
  Dir := ExpandConstant('{%USERPROFILE}\.rufus');
  ForceDirectories(Dir);
  SaveStringToFile(Dir + '\.certif',
    GetDateTimeString('yyyy-mm-dd hh:nn', '-', ':') + ' | ' + Ligne + #13#10, True);
end;

// Langue des messages, d'après rufus.ini ([Param_Poste] Version, = Param_Poste_Version côté
// code). Traduit : fr, en, es, pt (br -> pt) ; repli fr pour toute autre / si absent.
function LangueDepuisIni(): String;
var ini, v: String;
begin
  Result := 'fr';
  ini := ExpandConstant('{%USERPROFILE}\Documents\Rufus\Rufus.ini');
  if not FileExists(ini) then Exit;
  v := Lowercase(Trim(GetIniString('Param_Poste', 'Version', '', ini)));
  if (v = 'fr') or (v = 'en') or (v = 'es') or (v = 'pt') then Result := v
  else if v = 'br' then Result := 'pt';
end;

// Avertissement « serveur MySQL à mettre à jour », dans la langue du poste. Affiché UNIQUEMENT
// quand un MySQL local trop ancien (ou MariaDB) est détecté. Le message dit explicitement
// « si vous n'hébergez pas la base ici, ignorez » → plus besoin de détecter le rôle du poste.
//   True  = l'utilisateur accepte (Oui) : l'install se fait ; au 1er lancement, si ce poste
//           héberge la base, Rufus proposera la mise à jour du socle.
//   False = il refuse (Non) : l'installeur stoppe, l'ancien Rufus reste en place.
function ConsentementMajServeur(): Boolean;
var lang, titre, texte: String;
begin
  lang := LangueDepuisIni();
  if lang = 'en' then begin
    titre := 'MySQL server to update';
    texte := 'IMPORTANT' + #13#10#13#10
      + 'Rufus stores your patient data in a database - on this computer, on another computer of '
      + 'your network, or on a remote server. That database is managed by the MySQL server, '
      + 'required by Rufus, which Rufus installs itself on first launch.' + #13#10#13#10
      + 'If you do not intend to host the patient database on this computer, ignore this message.' + #13#10#13#10
      + 'This version of Rufus greatly strengthens password security and requires a MySQL server '
      + '>= 8.0.14 (MariaDB not supported). This computer already hosts a MySQL/MariaDB server that '
      + 'is too old or incompatible.' + #13#10#13#10
      + 'On first launch, Rufus will offer to update the server. This update erases the data and '
      + 'therefore requires a backup:' + #13#10
      + '  - if the database on this computer is a Rufus patient database, Rufus can back it up and '
      + 'restore it automatically;' + #13#10
      + '  - if it holds other data, back it up yourself, otherwise it will be permanently lost.' + #13#10#13#10
      + 'Do you want to continue installing Rufus?  (Yes = continue,  No = cancel)';
  end else if lang = 'es' then begin
    titre := 'Servidor MySQL por actualizar';
    texte := 'IMPORTANTE' + #13#10#13#10
      + 'Rufus almacena los datos de sus pacientes en una base de datos: en este equipo, en otro '
      + 'equipo de su red o en un servidor remoto. Esa base la gestiona el servidor MySQL, '
      + 'imprescindible para Rufus, que Rufus instala por sí mismo en el primer arranque.' + #13#10#13#10
      + 'Si no piensa alojar la base de pacientes en este equipo, ignore este mensaje.' + #13#10#13#10
      + 'Esta versión de Rufus refuerza enormemente la seguridad de las contraseñas y requiere un '
      + 'servidor MySQL >= 8.0.14 (MariaDB no compatible). Este equipo ya aloja un servidor '
      + 'MySQL/MariaDB demasiado antiguo o incompatible.' + #13#10#13#10
      + 'En el primer arranque, Rufus propondrá actualizar el servidor. Esta actualización borra los '
      + 'datos y exige una copia de seguridad:' + #13#10
      + '  - si la base de este equipo es una base de pacientes Rufus, Rufus podrá copiarla y '
      + 'restaurarla automáticamente;' + #13#10
      + '  - si contiene otros datos, haga usted mismo una copia, de lo contrario se perderán definitivamente.' + #13#10#13#10
      + '¿Desea continuar la instalación de Rufus?  (Sí = continuar,  No = cancelar)';
  end else if lang = 'pt' then begin
    titre := 'Servidor MySQL a atualizar';
    texte := 'IMPORTANTE' + #13#10#13#10
      + 'O Rufus guarda os dados dos seus pacientes numa base de dados - neste computador, noutro '
      + 'computador da sua rede ou num servidor remoto. Essa base é gerida pelo servidor MySQL, '
      + 'indispensável ao Rufus, que o Rufus instala por si próprio no primeiro arranque.' + #13#10#13#10
      + 'Se não tenciona alojar a base de pacientes neste computador, ignore esta mensagem.' + #13#10#13#10
      + 'Esta versão do Rufus reforça muito a segurança das palavras-passe e exige um servidor MySQL '
      + '>= 8.0.14 (MariaDB não suportado). Este computador já aloja um servidor MySQL/MariaDB '
      + 'demasiado antigo ou incompatível.' + #13#10#13#10
      + 'No primeiro arranque, o Rufus proporá atualizar o servidor. Esta atualização apaga os dados '
      + 'e exige uma cópia de segurança:' + #13#10
      + '  - se a base deste computador for uma base de pacientes Rufus, o Rufus poderá copiá-la e '
      + 'restaurá-la automaticamente;' + #13#10
      + '  - se contiver outros dados, faça você mesmo uma cópia, caso contrário serão definitivamente perdidos.' + #13#10#13#10
      + 'Deseja continuar a instalação do Rufus?  (Sim = continuar,  Não = cancelar)';
  end else begin
    titre := 'Serveur MySQL à mettre à jour';
    texte := 'IMPORTANT' + #13#10#13#10
      + 'Rufus stocke les données de vos patients dans une base de données - sur ce poste, sur un '
      + 'autre poste de votre réseau, ou sur un serveur distant. Cette base est gérée par le serveur '
      + 'MySQL, indispensable à Rufus, que Rufus installe lui-même à son premier lancement.' + #13#10#13#10
      + 'Si vous ne comptez pas héberger la base patients sur ce poste, ignorez ce message.' + #13#10#13#10
      + 'Cette version de Rufus renforce fortement la sécurité des mots de passe et nécessite un '
      + 'serveur MySQL >= 8.0.14 (MariaDB non pris en charge). Or ce poste héberge déjà un serveur '
      + 'MySQL/MariaDB trop ancien ou incompatible.' + #13#10#13#10
      + 'À son premier lancement, Rufus proposera de mettre à jour le serveur. Cette mise à jour '
      + 'efface les données et nécessite donc une sauvegarde :' + #13#10
      + '  - si la base de ce poste est une base patients Rufus, Rufus pourra la sauvegarder puis la '
      + 'restaurer automatiquement ;' + #13#10
      + '  - si elle contient d''autres données, sauvegardez-les vous-même, sinon elles seront définitivement perdues.' + #13#10#13#10
      + 'Voulez-vous continuer à installer Rufus ?  (Oui = continuer,  Non = annuler)';
  end;
  // MsgBox (Oui/Non) : fiable, boutons localisés par Windows. La question est portée par le texte.
  Result := (MsgBox(titre + #13#10#13#10 + texte, mbConfirmation, MB_YESNO) = IDYES);
end;

// True = on continue l'installation ; False = on l'abandonne (ancien Rufus intact).
// Logique simplifiée : on regarde seulement le MySQL LOCAL.
//   conforme (0) ou absent (2) → on installe sans rien dire ;
//   trop ancien / MariaDB (1)  → avertissement + consentement (Non → abandon).
function InitializeSetup(): Boolean;
var etat: Integer;
begin
  etat := ControleMySQLLocal();
  if etat <> 1 then begin
    EcritCertif('MySQL local conforme ou absent (etat=' + IntToStr(etat) + ') : installation sans avertissement');
    Result := True;
    Exit;
  end;
  // etat = 1 : MySQL local présent mais trop ancien (ou MariaDB) → avertissement.
  if ConsentementMajServeur() then begin
    EcritCertif('Avertissement MySQL ancien/MariaDB accepté : installation poursuivie');
    Result := True;
  end else begin
    EcritCertif('Avertissement MySQL ancien/MariaDB : installation annulée par l''utilisateur');
    Result := False;
  end;
end;
